# -*- coding: utf-8 -*-
"""Verification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t9TLgea09Vpy7NM0UFYi78ClWSxmylUc

Verification
"""

!pip install tensorflow-gpu

!nvidia-smi

from google.colab import drive
drive.mount('/content/drive')

dir_path='/content/drive/MyDrive/Trained_Model.h5'

#import library
import os
import cv2
import tensorflow as tf
import numpy as np
from keras.preprocessing import image
import matplotlib.pyplot as plt

def predict(img_path):
     labels={0: 'cardboard', 1: 'degradable', 2: 'glass', 3: 'metal', 4: 'paper', 5: 'plastic'}
     img_path = '/content/drive/MyDrive/validation/degradable/degradable (4).jpeg'

     img = image.load_img(img_path, target_size=(300, 300))
     img = image.img_to_array(img, dtype=np.uint8)
     img=np.array(img)/255.0
     plt.imshow(img.squeeze())
     
     model = tf.keras.models.load_model(dir_path)
     p=model.predict(img[np.newaxis, ...])
     pro=np.max(p[0], axis=-1)
     print("p.shape:",p.shape)
     print("prob",pro)
     predicted_class = labels[np.argmax(p[0], axis=-1)]
     #os.remove(img_path)
     print("classified label:",predicted_class)
     return(str(predicted_class)+" \n Probability:"+str(pro))
print(predict(img_path = '/content/drive/MyDrive/validation/degradable/degradable (4).jpeg'))